# ------------------------------------------------------------------------
# Copyright (c) 2022 megvii-model. All Rights Reserved.
# ------------------------------------------------------------------------
# Modified from BasicSR (https://github.com/xinntao/BasicSR)
# Copyright 2018-2020 BasicSR Authors
# ------------------------------------------------------------------------
# general settings
name: PMRID3-denoise
is_train: false
dist: false
model_type: ImageRestorationModel
scale: 1
num_gpu: 0 # set num_gpu: 0 for cpu mode
manual_seed: 10

# dataset and data loader settings
# network structures
network_g:
  type: PMRIDd3

# path
path:
  pretrain_network_g: models/weights/PMRIDd3-denoise.pth
  strict_load_g: true
  resume_state: ~

# validation settings
val:
  save_img: true
  grids: false
  use_image: false

  metrics:
    psnr: # metric name, can be arbitrary
      type: calculate_psnr
      crop_border: 0
      test_y_channel: false
    ssim:
      type: calculate_ssim
      crop_border: 0
      test_y_channel: false

# dist training settings
dist_params:
  backend: nccl
  port: 29500
